dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "2"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
branches:
  only: master
script:
  - cd decide
  - cp travis_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test --keepdb 
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: prueba-examen-reyblacua
  strategy: git
  apikey: $HEROKU_AUTH_TOKEN
  on:
    branch: master
